/*
 * Please do not edit this file.
 * It was generated using rpcgen.
 */

#include "comando.h"

bool_t
xdr_comando (XDR *xdrs, comando *objp)
{
	register int32_t *buf;

	 if (!xdr_int (xdrs, &objp->tam))
		 return FALSE;
	 if (!xdr_string (xdrs, &objp->elementos, ~0))
		 return FALSE;
	return TRUE;
}
