/*
 * This is sample code generated by rpcgen.
 * These are only templates and you can use them
 * as a guideline for developing your own functions.
 */

#include "comando.h"

char **
ejecucioncomando_1_svc(struct comando *argp, struct svc_req *rqstp)
{
	static char *result = NULL;
	struct comando argumento = *argp;
	
	/*
	 * insert server code here
	 */
    //Agrego logica del popen aqui
    FILE *fp;
    int status;
    char path[PATH_MAX] = {0};
    char comando[1024]={0};
       
	//printf("Valor comando: %s %d\n", argumento.elementos, strlen(argumento.elementos));
    strcpy(comando, argumento.elementos);

    printf("Comando a ejecutar: %s %d\n ", comando, strlen(comando));
    fp=popen(comando, "r");

	if (fp == NULL) {
           //Coloco result en null
          //result=NULL;
          return NULL;
        }
	
	result = malloc(PATH_MAX+1); //El 1 es para el null 
	strcpy(result, "");


    while (fgets(path, PATH_MAX, fp) != NULL && (strlen(result)+strlen(path))<PATH_MAX) {
        strcat(result, path);
    }

    printf("Resultado: %s\n", result);
 
	status = pclose(fp);
    if (status == -1) {
            /* Error reported by pclose() */
    } else {
            /* Use macros described under wait() to inspect `status' in ord$
             to determine success/failure of command executed by popen() */
    }
	
	return &result;
}
