/*
 * Please do not edit this file.
 * It was generated using rpcgen.
 */

#ifndef _COMANDO_H_RPCGEN
#define _COMANDO_H_RPCGEN

#include <rpc/rpc.h>


#ifdef __cplusplus
extern "C" {
#endif


struct comando {
	int tam;
	char *elementos;
};
typedef struct comando comando;

#define COMANDO_PRG 0x20000001
#define COMANDO_1 1

#if defined(__STDC__) || defined(__cplusplus)
#define ejecucionComando 1
extern  char ** ejecucioncomando_1(struct comando *, CLIENT *);
extern  char ** ejecucioncomando_1_svc(struct comando *, struct svc_req *);
extern int comando_prg_1_freeresult (SVCXPRT *, xdrproc_t, caddr_t);

#else /* K&R C */
#define ejecucionComando 1
extern  char ** ejecucioncomando_1();
extern  char ** ejecucioncomando_1_svc();
extern int comando_prg_1_freeresult ();
#endif /* K&R C */

/* the xdr functions */

#if defined(__STDC__) || defined(__cplusplus)
extern  bool_t xdr_comando (XDR *, comando*);

#else /* K&R C */
extern bool_t xdr_comando ();

#endif /* K&R C */

#ifdef __cplusplus
}
#endif

#endif /* !_COMANDO_H_RPCGEN */
